disabled_rules:
  - file_header
  - file_name
  - force_cast
  - force_try
  - prohibited_interface_builder
  - unowned_variable_capture
  - balanced_xctest_lifecycle
  # Prefer SwiftFormat
  - opening_brace
  - trailing_comma
  - sorted_imports
  - number_separator
opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - comment_spacing
  - computed_accessors_order
  - class_delegate_protocol
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - empty_xctest_method
  - explicit_enum_raw_value
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - file_name_no_space
  - flatmap_over_map_reduce
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - joined_default_parameter
  - last_where
  - let_var_whitespace
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_nimble
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

excluded:
  - TodoApp/DI/NeedleGenerated.swift
  - TodoApp/Resources/Generated

line_length:
  - 200 # warning
  - 300 # error

identifier_name:
  min_length: # only min_length
    error: 1 # only error
  excluded: # excluded via string array
    - id
    - URL
    - x
    - y
    - vc
    - on
    - db
  reporter: "xcode"
