name: Firebase-TodoApp
options:
  xcodeVersion: "12.0"
  deploymentTarget:
    iOS:  "14.0"
  developmentLanguage: ja

settings:
  base:
    SWIFT_VERSION: 5.0

targets:
  TodoApp:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.github.droibit.Firebase-TodoApp
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"${TARGET_NAME}/Resources/Preview Content\""
    sources:
      - path: TodoApp
        excludes:
          - "**/.gitignore"      
      - path: TodoApp/DI/NeedleGenerated.swift
        optional: true
        createIntermediateGroups: true       
    dependencies:
      - carthage: NeedleFoundation
      - framework: $SRCROOT/../shared/build/xcode-frameworks/Shared.framework
        embed: true
    preBuildScripts:
      - name: Run needle
        outputFiles:
          - $SRCROOT/$TARGET_NAME/DI/NeedleGenerated.swift
        script:  ./scripts/needle.sh
      - name: Pack for Xcode
        script:  ./scripts/packforxcode.sh
    postCompileScripts:
      - name: Run SwiftFormat
        script: ./scripts/swiftformat.sh
      - name: Run SwiftLint
        script: ./scripts/swiftlint.sh

schemes:
  TodoApp:
    build:
      targets:
        TodoApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Debug      