name: Firebase-TodoApp
options:
  xcodeVersion: "12.0"
  deploymentTarget:
    iOS:  "14.0"
  developmentLanguage: ja

settings:
  base:
    SWIFT_VERSION: 5.0
    OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC

targets:
  TodoApp:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.github.droibit.Firebase-TodoApp
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"${TARGET_NAME}/Resources/Preview Content\""
    sources:
      - path: TodoApp
        excludes:
          - "**/.gitignore"      
      - path: TodoApp/DI/NeedleGenerated.swift
        optional: true
        createIntermediateGroups: true
      - path: TodoApp/Resources/Google/GoogleService-Info.plist
        optional: true
        createIntermediateGroups: true
      - path: TodoApp/Resources/Generated/Strings+Generated.swift
        optional: true
        createIntermediateGroups: true
      - path: TodoApp/Resources/Generated/XCAssets+Generated.swift
        optional: true
        createIntermediateGroups: true         
    dependencies:
      - carthage: NeedleFoundation
      - framework: $SRCROOT/../shared/build/xcode-frameworks/Shared.framework
        embed: true
    preBuildScripts:
      - name: Run needle
        outputFiles:
          - $SRCROOT/$TARGET_NAME/DI/NeedleGenerated.swift
        script:  ./scripts/needle.sh
      - name: Run SwiftGen
        path: /bin/sh
        outputFiles:
          - $SRCROOT/$TARGET_NAME/Resources/Generated/Strings+Generated.swift
          - $SRCROOT/$TARGET_NAME/Resources/Generated/XCAssets+Generated.swift
        script: ./scripts/swiftgen.sh        
      - name: Pack for Xcode
        script:  ./scripts/packforxcode.sh
    postCompileScripts:
      - name: Run SwiftFormat
        script: ./scripts/swiftformat.sh
      - name: Run SwiftLint
        script: ./scripts/swiftlint.sh

schemes:
  TodoApp:
    build:
      targets:
        TodoApp: all
      # ref. https://github.com/firebase/firebase-ios-sdk/issues/6472  
      postActions:      
        - script: rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/Frameworks/FirebaseAnalytics.framework" &&
                  rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/Frameworks/GoogleAppMeasurement.framework" &&
                  rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/PlugIns/FirebaseAnalytics.framework" &&
                  rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/PlugIns/GoogleAppMeasurement.framework" &&
          name: Remove Firebase frameworks
          settingsTarget: TodoApp
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Debug      